---
title: "GeoNet Quake Search Data Pull Request"
author: "Thomas Rautao"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
### Pull the data from GeoNet Quake Search

library(readr)
library(dplyr)
library(lubridate)


dir.create(
  "geonet_monthly",
  showWarnings = FALSE
)


# NZ bounding box
bbox <- "163.5205,-49.1817,-176.9238,-32.2871"


# Monthly dates
months <- seq(
  as.Date("2001-01-01"),
  floor_date(Sys.Date(), "month"),
  by = "month"
)




# Download files for every month
for(i in seq_along(months)){

  start <- months[i]

  if(i < length(months)){
    end <- months[i+1]
  } else {
    end <- Sys.Date() + 1
  }


  outfile <- paste0(
    "geonet_monthly/",
    format(start,"%Y_%m"),
    ".csv"
  )


  if(file.exists(outfile)){
    message("Skipping ", outfile)
    next
  }


  message(
    "Downloading ",
    start,
    " to ",
    end
  )


  url <- paste0(
    "https://quakesearch.geonet.org.nz/csv?",
    "bbox=",
    bbox,
    "&startdate=",
    start,
    "T00:00:00",
    "&enddate=",
    end,
    "T00:00:00"
  )


  dat <- read_csv(
    url,
    show_col_types = FALSE
  )


  write_csv(
    dat,
    outfile
  )


  message(
    "Saved ",
    nrow(dat),
    " earthquakes"
  )


  Sys.sleep(1)

}

```

```{r}
### Combine all month files

files <- list.files(
  "geonet_monthly",
  pattern = "\\.csv$",
  full.names = TRUE
)


catalogue <- bind_rows(
  lapply(
    files,
    function(x) {
      
      read_csv(
        x,
        col_types = cols(
          publicid = col_character()
        ),
        show_col_types = FALSE
      )
      
    }
  )
)


# Remove duplicate earthquakes
catalogue <- catalogue %>%
  distinct(publicid, .keep_all = TRUE)


write_csv(
  catalogue,
  "GeoNet_catalogue_2001_present.csv"
)


cat(
  "\nComplete!\nTotal earthquakes:",
  nrow(catalogue)
)
```

```{r}
### Turn csv into data table
library(data.table)

catalogue <- fread(
  "GeoNet_catalogue_2001_present.csv",
  colClasses = list(character = "publicid")
)
```

```{r}
# Download GeoNet reported intensity data and join to catalogue

library(data.table)
library(dplyr)
library(lubridate)
library(httr)
library(jsonlite)
library(purrr)
library(readr)


# Create modern earthquake catalogue
# Filter for year >= 2012 as this is when the new publicid format is implemented and so able to retrieve intensities from GeoNet
# Filter for magnitude >= 3.0 as earthquakes weaker than this are unlikely to have been felt and so there won't be any reports, could potentially be raised to 3.5 or 4.

modern_quakes <- catalogue %>%
  mutate(
    origintime = ymd_hms(origintime),
    year = year(origintime)
  ) %>%
  filter(
    magnitude >= 3.0,
    year >= 2012
  )


cat(
  "Modern earthquakes available:",
  nrow(modern_quakes),
  "\n"
)



# Download GeoNet reported intensity

get_intensity <- function(id){

  # Prevent excessive requests
  Sys.sleep(0.2)


  url <- paste0(
    "https://api.geonet.org.nz/intensity?",
    "type=reported&publicID=",
    id
  )


  response <- GET(
    url,
    add_headers(
      Accept = "application/vnd.geo+json;version=2"
    )
  )


  # Return NULL if request fails
  if(status_code(response) != 200){
    return(NULL)
  }


  txt <- content(
    response,
    "text",
    encoding = "UTF-8"
  )


  geo <- fromJSON(
    txt,
    flatten = TRUE
  )


  # Return NULL if no felt reports exist
  if(
    is.null(geo$features) ||
    length(geo$features) == 0
  ){
    return(NULL)
  }


  intensity <- as.data.frame(
    geo$features
  )


  # Add earthquake ID
  intensity$publicid <- id


  intensity

}




# Download intensity data for all earthquakes (replaced below)
#cat(
#  "Downloading intensity data...\n"
#)


# Download intensity data with progress reporting

total_quakes <- nrow(modern_quakes)

cat(
  "Downloading intensity data for",
  total_quakes,
  "earthquakes...\n"
)


intensity_list <- map(
  seq_along(modern_quakes$publicid),
  function(i){

    if(i %% 100 == 0 || i == 1){
      cat(
        "Processing earthquake",
        i,
        "of",
        total_quakes,
        "\n"
      )
    }


    get_intensity(
      modern_quakes$publicid[i]
    )

  }
)


cat(
  "Intensity download complete\n"
)



# Combine observations

intensity_data <- bind_rows(
  intensity_list
)


cat(
  "Intensity observations downloaded:",
  nrow(intensity_data),
  "\n"
)


print(
  names(intensity_data)
)




# Save raw intensity observations

write_csv(
  intensity_data,
  "GeoNet_reported_intensity_observations.csv"
)



# Create earthquake-level MMI summary

quake_mmi_summary <- intensity_data %>%
  group_by(publicid) %>%
  summarise(

    # Highest reported Modified Mercalli Intensity
    max_mmi = max(
      properties.mmi,
      na.rm = TRUE
    ),

    # Total number of felt reports
    total_reports = sum(
      properties.count,
      na.rm = TRUE
    ),

    .groups = "drop"
  )




# Add available MMI count columns

mmi_columns <- grep(
  "^properties\\.count_mmi\\.",
  names(intensity_data),
  value = TRUE
)


for(col in mmi_columns){

  new_name <- paste0(
    "mmi_",
    sub(
      "properties\\.count_mmi\\.",
      "",
      col
    ),
    "_reports"
  )


  temp <- intensity_data %>%
    group_by(publicid) %>%
    summarise(
      value = sum(
        .data[[col]],
        na.rm = TRUE
      ),
      .groups = "drop"
    )


  names(temp)[2] <- new_name


  quake_mmi_summary <- quake_mmi_summary %>%
    left_join(
      temp,
      by = "publicid"
    )

}



# Join intensity summary back to earthquake catalogue

modern_quakes_with_mmi <- modern_quakes %>%
  left_join(
    quake_mmi_summary,
    by = "publicid"
  )




# Save final earthquake-level dataset

write_csv(
  modern_quakes_with_mmi,
  "GeoNet_modern_quakes_with_MMI_summary.csv"
)




# Display results

cat(
  "\nComplete!\n",
  "Earthquakes processed:",
  nrow(modern_quakes),
  "\n",
  "Earthquakes with intensity data:",
  n_distinct(intensity_data$publicid),
  "\n"
)


head(
  modern_quakes_with_mmi
)
```

```{r}
### Create one-row-per-earthquake MMI summary from GeoNet intensity

library(dplyr)



# Identify available MMI report columns returned by GeoNet

mmi_columns <- grep(
  "^properties\\.count_mmi\\.",
  names(intensity_data),
  value = TRUE
)


# Display available MMI levels
print(mmi_columns)




# Create summary table

quake_mmi_summary <- intensity_data %>%
  group_by(publicid) %>%
  summarise(

    # Maximum reported Modified Mercalli Intensity
    max_mmi = max(
      properties.mmi,
      na.rm = TRUE
    ),

    # Total number of felt reports
    total_reports = sum(
      properties.count,
      na.rm = TRUE
    ),

    .groups = "drop"
  )



# Add MMI level report counts


for(col in mmi_columns){

  # Create a cleaner name:
  # properties.count_mmi.4 -> mmi_4_reports

  new_name <- paste0(
    "mmi_",
    sub(
      "properties\\.count_mmi\\.",
      "",
      col
    ),
    "_reports"
  )


  # Summarise this MMI level
  temp <- intensity_data %>%
    group_by(publicid) %>%
    summarise(
      value = sum(
        .data[[col]],
        na.rm = TRUE
      ),
      .groups = "drop"
    )


  names(temp)[2] <- new_name


  # Join onto summary table
  quake_mmi_summary <- quake_mmi_summary %>%
    left_join(
      temp,
      by = "publicid"
    )
}




# Join intensity summary back onto earthquake catalogue

modern_quakes_with_mmi <- modern_quakes %>%
  left_join(
    quake_mmi_summary,
    by = "publicid"
  )




# Save final earthquake-level dataset

write_csv(
  modern_quakes_with_mmi,
  "GeoNet_modern_quakes_with_MMI_summary.csv"
)




# Display result

head(
  modern_quakes_with_mmi
)
```

```{r}
# Reorder columns to place important info first

modern_quakes_with_mmi <- modern_quakes_with_mmi %>%
  select(
    publicid,
    origintime,
    magnitude,
    max_mmi,
    total_reports,
    depth,
    longitude,
    latitude,
    everything()
  )
```

